app/short_link/models.py
from datetime import datetime
from sqlalchemy import Column, Integer, String, DateTime

from app.database.db import db
from app.utils.keygen import generate_random_key


class Link(db.Model):
    """
    A class used to represent a link.
    A short link is automatically generated before saving.
    """
    __tablename__ = 'links'

    id = Column(Integer, primary_key=True)
    long_url = Column(String(512))
    short_url = Column(String(8), unique=True)
    clicks = Column(Integer, default=0)
    created_at = Column(DateTime, default=datetime.now)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.short_url = self.create_short_url()

    def create_short_url(self):
        """Check the existence and uniqueness of the short URL"""
        key = generate_random_key()
        while Link.query.filter_by(short_url=key).first() is not None:
            key = generate_random_key()

        return key

app/short_link/forms.py
from flask_wtf import Form
from wtforms import StringField
from wtforms.validators import DataRequired, URL


class LinkCreateForm(Form):
    """
    Class LinkCreateForm provides field construction,
    validation, and data and error proxying.
    """
    long_url = StringField(
        label='Long URL',
        validators=[DataRequired(message="The field is required to fill in"),
                    URL(message="Enter the correct url")],
        description="Name")
    short_url = StringField(label='Short URL', description="Name")

app/short_link/controllers.py
from flask import (
    Blueprint,
    render_template,
    request,
    flash,
    abort,
    redirect,
    url_for,
    current_app,
)
from sqlalchemy.exc import SQLAlchemyError

from app.short_link.models import Link
from app.database.db import db
from app.short_link.forms import LinkCreateForm

module = Blueprint('links', __name__, url_prefix ='/link_shortener')


def log_error(*args, **kwargs):
    current_app.logger.error(*args, **kwargs)

@module.route('/<short_url>', methods=['GET'])
def redirect_to_url(short_url):
    link = None
    try:
        link = Link.query.filter_by(short_url=short_url).first_or_404()
        link.clicks = link.clicks + 1
        db.session.commit()
    except SQLAlchemyError as e:
        log_error('Error while querying database', exc_info=e)
        flash('Во время запроса произошла непредвиденная ошибка.', 'danger')
        abort(500)
    return redirect(link.original_url)

@module.route('/', methods=['GET'])
def index():
    links = None
    try:
        links = Link.query.order_by(Link.created_at).all()
        db.session.commit()
    except SQLAlchemyError as e:
        log_error('Error while querying database', exc_info=e)
        flash('Во время запроса произошла непредвиденная ошибка.', 'danger')
        abort(500)
    return render_template('entity/index.html', object_list=links)

@module.route('/shorten', methods=['POST'])
def create():
    form = LinkCreateForm(request.form)
    try:
        if request.method == 'POST' and form.validate():
            link = Link(**form.data)
            db.session.add(link)
            db.session.flush()
            id = link.id
            db.session.commit()
            flash('Запись была успешно добавлена!', 'success')
            return redirect(url_for('entity.view', id=id))
    except SQLAlchemyError as e:
        log_error('There was error while querying database', exc_info=e)
        db.session.rollback()
        flash('Произошла непредвиденная ошибка во время запроса к базе данных', 'danger')
    return render_template('entity/create.html', form=form)

app/short_link/views.py
from flask import (abort, Blueprint, current_app, redirect, request,
                   render_template)
from http import HTTPStatus
from sqlalchemy.exc import SQLAlchemyError

from app.short_link.models import Link
from app.database.db import db
from app.short_link.forms import LinkCreateForm
from config import Config


module = Blueprint('views', __name__, url_prefix='/link_shortener')


def log_error(*args, **kwargs):
    current_app.logger.error(*args, **kwargs)


@module.route('/<short_url>', methods=['GET'])
def forward_to_target_url(short_url: str):
    """Forward to target URL"""
    link = None
    try:
        link = Link.query.filter_by(short_url=short_url).first_or_404()
        link.clicks += 1
        db.session.commit()
    except SQLAlchemyError as e:
        log_error('Error while querying database', exc_info=e)
        abort(HTTPStatus.NOT_FOUND)
    return redirect(link.long_url)


@module.route('/', methods=['GET'])
def index():
    """Get all URLs"""
    links = None
    try:
        links = Link.query.order_by(Link.created_at.desc())
        page = request.args.get('page', 1, type=int)
        pagination = db.paginate(links, page=page, per_page=5)
        db.session.commit()
    except SQLAlchemyError as e:
        log_error('Error while querying database', exc_info=e)
        abort(HTTPStatus.INTERNAL_SERVER_ERROR)

    return render_template('link/index.html', pagination=pagination)


@module.route('/shorten', methods=['GET', 'POST'])
def create_url():
    """Create a short URL"""
    form = LinkCreateForm(request.form)
    try:
        if (form.validate() and Link.query.filter_by(
            long_url=form.data['long_url']
        ).first() is None):
            db.session.add(Link(**form.data))
            db.session.commit()

        links = Link.query.order_by(Link.created_at.desc())
        page = request.args.get('page', 1, type=int)
        pagination = db.paginate(links, page=page, per_page=5)
        object = Link.query.filter_by(long_url=form.data['long_url']).first()
    except SQLAlchemyError as e:
        log_error('There was error while querying database', exc_info=e)
        db.session.rollback()

    base_url = Config.BASE_URL+module.url_prefix

    return render_template('link/shortened_link.html',
                           object=object,
                           pagination=pagination,
                           base_url=base_url,
                           form=form)

app/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
  </head>
  <header>
    Link Shortener
  </header>
  <body>
    <main> 
      {% block content %}{% endblock %}
    </main>
  </body>
  

  

app/templates/includes/error.html
{% if form.errors %}
{% for field in form %}
  {% for error in field.errors %}            
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
  <div class="alert alert-danger">
    {{ error|escape }}
  </div>
{% endfor %}
{% endif %}

app/templates/includes/pagination.html
<nav aria-label="Page navigation">
    <ul class="pagination">
        <li class="page-item {% if not pagination.has_prev %}disabled{% endif %}">
            <a class="page-link" href="{{ url_for('views.index', page=pagination.prev_num) }}" tabindex="-1">Previous</a>
        </li>
        {% for number in pagination.iter_pages() %}
            {% if pagination.page != number %}
                <li class="page-item"><a class="page-link" href="{{ url_for('views.index', page=number) }}">{{ number }}</a></li>
            {% else %}
                <li class="page-item active">
                    <a class="page-link" href="{{ url_for('views.index', page=number) }}">{{ number }} <span class="sr-only">(current)</span></a>
                </li>
            {% endif %}
        {% endfor %}
        <li class="page-item {% if not pagination.has_next %}disabled{% endif %}">   
            <a class="page-link" href="{{ url_for('views.index', page=pagination.next_num) }}">Next</a>
        </li>
    </ul>
</nav>

app/templates/link/includes/link_table.html
<table class="table table-sm">
    <thead>
        <h4 class="text-center">History</h4>
    <tr></tr>
    </thead>
    <tbody>
    {% for obj in pagination.items %}
    <tr>
        <th scope="row">
            {{ obj.long_url }} >>>
            <a href="{{obj.short_url}}">
                <span style="color:blue">
                    http://127.0.0.1:5000/link_shortener/{{ obj.short_url }}
                </span>
            </a>
        </th>
        <td>{{ obj.created_at.strftime("%d-%m-%Y %H:%M:%S") }}</td>
        <td><span style="color:blue">{{ obj.clicks }}</span></td>
    </tr>
    {% endfor %}
    </tbody>
</table>

app/templates/link/index.html
{% extends 'bootstrap/base.html' %}

{% block title %} Link Shortener {% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-4 col-lg-offset-4">
            <h1 class="text-center">Link Shortener</h1>
            <form method="POST" action="{{ url_for('views.create_url') }}">
                <div class="form-group">
                    <input type="text" name="long_url" class="form-control" id="long_url" placeholder="Long url">
                </div>
                <div class="form-group">
                <fieldset disabled>
                    <input type="short_url" class="form-control" id="short_url" placeholder="Short url">
                </fieldset>
                </div>
                <button type="submit" class="btn btn-primary btn-block">Short</button>
            </form>
        </div>
    </div>
    <div class="row justify-content-center"></div>
        {% include 'link/includes/link_table.html' %}
        {% include 'includes/pagination.html' %}
    </div> 
</div>
{% endblock %}

app/templates/link/shortened_link.html
{% extends 'bootstrap/base.html' %}

{% block title %} Link Shortener {% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-4 col-lg-offset-4">
            <a href="{{ url_for('views.index') }}"><h1 class="text-center">Link Shortener</h1></a>
            <form method="POST" action="{{ url_for('views.create_url') }}">
                <div class="form-group">
                    {% include 'includes/error.html' %}
                    <input type="text" name="long_url" class="form-control" value="{{object.long_url}}">
                </div>
                <div class="form-group">
                    <input type="text" name="short_url" class="form-control" value="{{base_url}}{{object.short_url}}">
                </div>
                <button type="submit" class="btn btn-primary btn-block">Short</button>
            </form>
        </div>
    </div>
    <div class="row justify-content-center"></div>
        {% include 'link/includes/link_table.html' %}
        {% include 'includes/pagination.html' %}
    </div>
   
</div>
{% endblock %}